[package]
name = "blackstone"
version = "0.1.0"
edition = "2021"
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/BlackstoneDF/blackstone"
homepage = "https://github.com/BlackstoneDF/blackstone"
description = "A programming language designed for the DiamondFire Minecraft server."

[dependencies]
base64 = "0.21.0"
lazy_static = "1.4.0"
libflate = "1.3.0"