[package]
name = "blackstone-df"
version = "0.1.0"
edition = "2021"
license = "Apache 2.0"
readme = "README.md"
repository = "https://github.com/BlackstoneDF/blackstone"
homepage = "https://github.com/BlackstoneDF/blackstone"
description = "A programming language designed for the DiamondFire Minecraft server."

# Compile for full blackstone name
[[bin]]
name = "blackstone"
path = "src/main.rs"

# Compile for shorthand bl name
[[bin]]
name = "bl"
path = "src/main.rs"

[dependencies]
base64 = "0.21.0"
lazy_static = "1.4.0"
libflate = "1.3.0"